lets see if this works

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -165,6 +165,22 @@ jobs:
       - name: Download Files
         uses: actions/download-artifact@v4
 
+      - name: Verify
+        run: |
+          ls -R .
+          if (!(Test-Path -Path "UKMCL-Windows-Installer-en_US.exe")) {
+            echo "ERROR: Windows installer not found"
+            exit 1
+          }
+          if (!(Test-Path -Path "UKMCL-Linux-Installer-en_US.deb")) {
+            echo "ERROR: Linux installer not found!"
+            exit 1
+          }
+          if (!(Test-Path -Path "UKMCL-MacOS-Installer-en_US.dmg")) {
+            echo "ERROR: MacOS installer not found!"
+            exit 1
+          }
+
       - name: Create Release
         uses: "marvinpinto/action-automatic-releases@v1.2.0"
         with:
